#  1.ECRIRE UNE FONCTION QUI PREND UNE LISTE EN PARAMETRE ET QUI RETOURNE  LA LISTE SANS DOUBLONS

In [1]:
def doublon_sup(liste):
    liste_sans_doublon =[]
    for i in liste:
        if i not in liste_sans_doublon:
            liste_sans_doublon.append(i)            
    return liste_sans_doublon

In [2]:
doublon_sup([1,1,1,2,2,3,3])

[1, 2, 3]

  # 2. QUELQUES NOTIONS NUMPY

In [3]:
import numpy as np

# CREATION D'UN TABLEAU NUMPY

In [4]:
A=np.array([[1,3,7],[4,2,6],[8,9,0]],dtype="float")

In [5]:
A

array([[1., 3., 7.],
       [4., 2., 6.],
       [8., 9., 0.]])

In [6]:
#dimension de A
A.shape

(3, 3)

In [7]:
#type des elements de A
A.dtype

dtype('float64')

In [8]:
#Forcer le type des elements de la matrice en float a la creation

A=np.array([[1,3,7],[4,2,6],[8,9,0]],dtype="float")


In [9]:
A.dtype

dtype('float64')

In [10]:
#Forcer le type des elements de la matrice en float apres la creation

A = A.astype('float64')
A.dtype

dtype('float64')

In [11]:
#nombre d'éléments a l'interieur du tableau et nombre de dimension (ce sont des objets)

print(A.size,A.ndim)

9 2


In [12]:
#somme des elements de A
A.sum()

40.0

In [13]:
A.prod()

0.0

In [14]:
A.min()

0.0

In [15]:
A.max()

9.0

In [16]:
A.mean()

4.444444444444445

In [17]:
A.var()

9.135802469135804

In [18]:
A.std()

3.02254900194121

In [19]:
np.median(A)

4.0

In [20]:
#NUMPY est un package qui contient des modules,des objets et des methodes
#module est un concentré de methode organiser par nom
#les methodes 

In [21]:
#Faire la somme par ligne 

In [22]:
A.sum(axis=1)

array([11., 12., 17.])

In [23]:
A

array([[1., 3., 7.],
       [4., 2., 6.],
       [8., 9., 0.]])

In [24]:
#Extraction d'element de la matrice
centre=A[1,1]
centre

2.0

In [25]:
LIGNE=A[1,:]

In [26]:
LIGNE

array([4., 2., 6.])

In [27]:
mat=A[1:3,0:2]

In [28]:
mat

array([[4., 2.],
       [8., 9.]])

In [29]:
mat_1=A[1:3,::2]
mat_1

array([[4., 6.],
       [8., 0.]])

In [30]:
mat_2=A[[1,2],::2]

In [31]:
mat_2

array([[4., 6.],
       [8., 0.]])

In [32]:
#un masque
A<5

array([[ True,  True, False],
       [ True,  True, False],
       [False, False,  True]])

In [33]:
#remplacer toutes les valeurs de la matrice inferieur à 5 par 0
A[A<5]=0

In [34]:
A

array([[0., 0., 7.],
       [0., 0., 6.],
       [8., 9., 0.]])

In [35]:
#matrice rempli de 0

mat_nulle=np.zeros((3,3))


In [36]:
mat_nulle

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
#matrice rempli de 1

mat_1=np.ones((3,3))

In [38]:
mat_1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [39]:
#matrice rempli de 5

mat_5=np.full((3,3),5)


In [40]:
mat_5

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [41]:
mat_5=5*mat_1

In [42]:
mat_5

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [43]:
#matrice(3,3) de nombre impaire allant de 1 à 17

mat_imp=np.arange(1,18,2,dtype="float").reshape((3,3))


In [45]:
mat_imp

array([[ 1.,  3.,  5.],
       [ 7.,  9., 11.],
       [13., 15., 17.]])

In [54]:
#transformer une matrice en vecteur

mat_imp.ravel()


array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17.])

In [56]:
mat_imp.flatten()

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17.])

In [62]:
#concatener par ligne

fusion_1 = np.concatenate((mat_1,mat_nulle) ,axis=1)


In [63]:
fusion_1

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [64]:
#concatener par colonne

fusion_2= np.concatenate((mat_1,mat_nulle) ,axis=0)


In [65]:
fusion_2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# INITIATION A PANDAS

In [67]:
#importation de la librairie pandas

import pandas as pd


In [68]:
#obtenir le repertoire de travail

import os
os.getcwd()


'C:\\Users\\Admin\\Documents'

In [69]:
dataset=pd.read_table('heart.txt')

In [74]:
dataset

age      sexe  pression  cholester sucre electro  taux_max angine  \
0     58  masculin       100        234     A       A       156    non   
1     41   feminin       130        204     A       C       172    non   
2     58  masculin       150        270     A       C       111    oui   
3     53  masculin       140        203     B       C       155    oui   
4     41  masculin       130        214     A       C       168    non   
..   ...       ...       ...        ...   ...     ...       ...    ...   
265   62   feminin       140        268     A       C       160    non   
266   62  masculin       130        231     A       A       146    non   
267   64  masculin       110        211     A       C       144    oui   
268   63   feminin       150        407     A       C       154    non   
269   35   feminin       138        183     A       A       182    non   

     depression  pic vaisseau     coeur  
0             1    1        B  presence  
1            14    1        A   absence  
2             8    1        A  presence  
3            31    3        A  presence  
4            20    2        A   absence  
..          ...  ...      ...       ...  
265          36    3        C  presence  
266          18    2        D   absence  
267          18    2        A   absence  
268          40    2        D  presence  
269          14    1        A   absence  

[270 rows x 12 columns]

In [75]:
#afficher les 5 dernieres lignes du tableau

dataset.tail()


age      sexe  pression  cholester sucre electro  taux_max angine  \
265   62   feminin       140        268     A       C       160    non   
266   62  masculin       130        231     A       A       146    non   
267   64  masculin       110        211     A       C       144    oui   
268   63   feminin       150        407     A       C       154    non   
269   35   feminin       138        183     A       A       182    non   

     depression  pic vaisseau     coeur  
265          36    3        C  presence  
266          18    2        D   absence  
267          18    2        A   absence  
268          40    2        D  presence  
269          14    1        A   absence

In [76]:
#Afficher le type des variables 

dataset.dtypes


age            int64
sexe          object
pression       int64
cholester      int64
sucre         object
electro       object
taux_max       int64
angine        object
depression     int64
pic            int64
vaisseau      object
coeur         object
dtype: object

In [80]:
#Afficher le nombre de lignes et de colonne et liste des colonnes
print(dataset.shape,dataset.columns)

(270, 12) Index(['age', 'sexe', 'pression', 'cholester', 'sucre', 'electro', 'taux_max',
       'angine', 'depression', 'pic', 'vaisseau', 'coeur'],
      dtype='object')


In [89]:
#afficher les statistiques descriptives du dataframe
import numpy as np
dataset.describe(include="all")

age      sexe    pression   cholester sucre electro  \
count   270.000000       270  270.000000  270.000000   270     270   
unique         NaN         2         NaN         NaN     2       3   
top            NaN  masculin         NaN         NaN     A       C   
freq           NaN       183         NaN         NaN   230     137   
mean     54.433333       NaN  131.344444  249.659259   NaN     NaN   
std       9.109067       NaN   17.861608   51.686237   NaN     NaN   
min      29.000000       NaN   94.000000  126.000000   NaN     NaN   
25%      48.000000       NaN  120.000000  213.000000   NaN     NaN   
50%      55.000000       NaN  130.000000  245.000000   NaN     NaN   
75%      61.000000       NaN  140.000000  280.000000   NaN     NaN   
max      77.000000       NaN  200.000000  564.000000   NaN     NaN   

          taux_max angine  depression         pic vaisseau    coeur  
count   270.000000    270  270.000000  270.000000      270      270  
unique         NaN      2         NaN         NaN        4        2  
top            NaN    non         NaN         NaN        A  absence  
freq           NaN    181         NaN         NaN      160      150  
mean    149.677778    NaN   10.500000    1.585185      NaN      NaN  
std      23.165717    NaN   11.452098    0.614390      NaN      NaN  
min      71.000000    NaN    0.000000    1.000000      NaN      NaN  
25%     133.000000    NaN    0.000000    1.000000      NaN      NaN  
50%     153.500000    NaN    8.000000    2.000000      NaN      NaN  
75%     166.000000    NaN   16.000000    2.000000      NaN      NaN  
max     202.000000    NaN   62.000000    3.000000      NaN      NaN

In [90]:
##Au cas ou on voudrais exclure les variables quantitative

In [92]:
dataset.describe(exclude=np.number)

sexe sucre electro angine vaisseau    coeur
count        270   270     270    270      270      270
unique         2     2       3      2        4        2
top     masculin     A       C    non        A  absence
freq         183   230     137    181      160      150

In [100]:
dataset.isna().sum()

age           0
sexe          0
pression      0
cholester     0
sucre         0
electro       0
taux_max      0
angine        0
depression    0
pic           0
vaisseau      0
coeur         0
dtype: int64